#!/bin/bash

readonly Static_IP=192.168.42.1/24
readonly  RED='\033[0;31m'
readonly  NC='\033[0m' # No Color


function Install() {
  if [ $(dpkg-query -W -f='${Status}' $1 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "$1 is not installed.. installing.."
    apt-get install --yes $1
  else
    echo "$1 is already installed.. skipping"
  fi
  if [ $(dpkg-query -W -f='${Status}' $1 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
    echo "${RED}Something went wrong while installing $1.."
    exit 
  fi
}
function FindLine() { #par1 = searchterm, par2 = filename
  lineResults=$(awk "/$1/{ print NR; exit }" $2)
  echo $lineResults
}

#install AccessPoint and DNS/DHCP services
Install dnsmasq
Install hostapd

#set static ip
echo "Setting static ip $Static_IP for wlan0.."
lineNr=$(FindLine wlan0 /etc/dhcpcd.conf)
lineNrCount=${#lineNr}
if [ $lineNrCount -eq 0 ]; then
  echo "interface wlan0" >> /etc/dhcpcd.conf
  echo "    static ip_address=$Static_IP" >> /etc/dhcpcd.conf
  echo "done.."
else
  printf "${RED}It seems there is already a setting for wlan0 in /etc/dhcpcd.conf at line $lineNr.\n"
  printf "You should probably ask our lord and savior Erwin Damsma for assistance${NC}\n"
fi

#prevent wpa_supplicant from running and interfering with setting up wlan0 in AP mode
lineNr=$(FindLine wlan0 /etc/network/interfaces)
if [ ${#lineNr} -ne 0 ]; then
  replaceLine=$(sed "$((lineNr + 2))q;d" /etc/network/interfaces)
  echo "Backing up /etc/network/interfaces to /etc/network/interfaces.bkp"
  cp /etc/network/interfaces /etc/network/interfaces.bkp
  echo "Commenting \"$replaceLine\" in /etc/network/interfaces"
  sed "$((lineNr + 2))s/.*/#/" /etc/network/interfaces > /etc/network/interfaces.tmp
  mv /etc/network/interfaces.tmp /etc/network/interfaces
fi

#Configure hostapd
echo "configuring hostapd"
cp Erwin_Script_Resources/hostapd.conf /etc/hostapd/hostapd.conf

#Set hostapd config file location for boot-time
lineNr=$(FindLine \#DAEMON_CONF=\"\" /etc/default/hostapd)
if [ ${#lineNr} -ne 0 ]; then
  echo "Backing up /etc/default/hostapd to /etc/default/hostapd.bkp"
  cp /etc/default/hostapd /etc/default/hostapd.bkp
  echo "Setting DAEMON_CONF in /etc/default/hostapd"
  sed "$((lineNr))s/.*/DAEMON_CONF=\"\/etc\/hostapd\/hostapd.conf\"/" /etc/default/hostapd > /etc/default/hostapd.tmp
  mv /etc/default/hostapd.tmp /etc/default/hostapd
fi

#configure DNSMASQ
echo "Backing up /etc/dnsmasq.conf to /etc/dnsmasq.bkp"
mv /etc/dnsmasq.conf /etc/dnsmasq.bkp
echo "Overwriting dnsmasq with file from resources"
cp Erwin_Script_Resources/dnsmasq.conf /etc/dnsmasq.conf

: <<'END' 
start of commented part

#set up IPV4 forwaring
lineNr=$(FindLine net.ipv4.ip_forward=1 /etc/sysctl.conf)
if [ ${#lineNr} -ne 0 ]; then
  echo "Backing up /etc/sysctl.conf to /etc/sysctl.conf.bkp"
  cp /etc/sysctl.conf /etc/sysctl.conf.bkp
  echo "removing \# from \"net.ipv4.ip_forward=1\""
  sed "$((lineNr))s/.*/tekst/" /etc/sysctl.conf > /etc/sysctl.conf.tmp
  mv /etc/sysctl.conf.tmp /etc/sysctl.conf
fi

#Share pi's eth0 network to wlan0
echo "sharing the eth0 connection with connected clients on wlan0"
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
sh -c "iptables-save > /etc/iptables.ipv4.nat"
cp Erwin_Script_Resources/70-ipv4-nat /lib/dhcpcd/dhcpcd-hooks/70-ipv4-nat

end of commented part
END

#start services
echo "Done! starting services hostapd and dnsmasq!"
service hostapd start
service dnsmasq start
echo "AP \"ScarJo-AP\" is now active with password \"sjoerderwin\""

#ending message
echo "Please reboot."
